"""agent output components

Revision ID: 15a3306fac25
Revises: 901f9a92f5e0
Create Date: 2026-10-08 21:57:23.222939
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "15a3306fac25"
down_revision: str | None = "901f9a92f5e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_outputs",
        sa.Column("components", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_outputs", "components")
    # ### end Alembic commands ###
