"""golive state

Revision ID: 385fa03639c1
Revises: 22620f680eec
Create Date: 2026-10-09 00:28:07.426324
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "385fa03639c1"
down_revision: str | None = "22620f680eec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "risk_state",
        sa.Column("mode", sa.String(length=8), nullable=False, server_default="shadow"),
    )
    op.add_column("risk_state", sa.Column("live_since", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "risk_state", sa.Column("live_selftest_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "risk_state", sa.Column("last_golive_check", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "risk_state",
        sa.Column("golive_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("risk_state", "golive_report")
    op.drop_column("risk_state", "last_golive_check")
    op.drop_column("risk_state", "live_selftest_at")
    op.drop_column("risk_state", "live_since")
    op.drop_column("risk_state", "mode")
    # ### end Alembic commands ###
