"""risk state

Revision ID: 50fbca293312
Revises: 15a3306fac25
Create Date: 2026-10-08 21:59:41.430189
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "50fbca293312"
down_revision: str | None = "15a3306fac25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "risk_rule_hits",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cycle_id", sa.BigInteger(), nullable=True),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("asset", sa.String(length=10), nullable=True),
        sa.Column("rule", sa.String(length=40), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("effect", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_risk_rule_hits_cycle", "risk_rule_hits", ["cycle_id"], unique=False)
    op.create_table(
        "risk_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("starting_capital", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("peak_equity", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("paused_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pause_count_30d", sa.Integer(), nullable=False),
        sa.Column("last_pause_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("half_risk_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("emergency_brake", sa.Boolean(), nullable=False),
        sa.Column("brake_reason", sa.Text(), nullable=True),
        sa.Column("day_locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("leverage_ceiling", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("risk_state")
    op.drop_index("ix_risk_rule_hits_cycle", table_name="risk_rule_hits")
    op.drop_table("risk_rule_hits")
    # ### end Alembic commands ###
