"""m1 data layer

Revision ID: 652b91d87761
Revises:
Create Date: 2026-10-08 21:00:19.114391
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "652b91d87761"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_equity", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("quote_balance", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("coins", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("open_orders", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_account_snapshots_ts"), "account_snapshots", ["ts"], unique=False)
    op.create_table(
        "candles",
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("interval", sa.String(length=4), nullable=False),
        sa.Column("open_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("high", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("low", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("close", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("volume", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("turnover", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("symbol", "interval", "open_time"),
    )
    op.create_table(
        "data_sources",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("consecutive_errors", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "fetch_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=True),
        sa.Column("rows", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_fetch_runs_source_started", "fetch_runs", ["source", "started_at"], unique=False
    )
    op.create_table(
        "macro_observations",
        sa.Column("series", sa.String(length=40), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("series", "date"),
    )
    op.create_table(
        "orderbook_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mid", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("spread_bps", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("depth_bid_2pct", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("depth_ask_2pct", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("bids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("asks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_orderbook_symbol_ts", "orderbook_snapshots", ["symbol", "ts"], unique=False)
    op.create_table(
        "polymarket_markets",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("condition_id", sa.String(length=80), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("outcomes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("token_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("closed", sa.Boolean(), nullable=False),
        sa.Column("asset", sa.String(length=10), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_polymarket_markets_asset"), "polymarket_markets", ["asset"], unique=False
    )
    op.create_table(
        "polymarket_prices",
        sa.Column("market_id", sa.String(length=32), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("prices", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("volume_24h", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("liquidity", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.ForeignKeyConstraint(["market_id"], ["polymarket_markets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("market_id", "ts"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("polymarket_prices")
    op.drop_index(op.f("ix_polymarket_markets_asset"), table_name="polymarket_markets")
    op.drop_table("polymarket_markets")
    op.drop_index("ix_orderbook_symbol_ts", table_name="orderbook_snapshots")
    op.drop_table("orderbook_snapshots")
    op.drop_table("macro_observations")
    op.drop_index("ix_fetch_runs_source_started", table_name="fetch_runs")
    op.drop_table("fetch_runs")
    op.drop_table("data_sources")
    op.drop_table("candles")
    op.drop_index(op.f("ix_account_snapshots_ts"), table_name="account_snapshots")
    op.drop_table("account_snapshots")
    # ### end Alembic commands ###
