"""decision action width

Revision ID: 76d3c340ecde
Revises: ebf02b9befa8
Create Date: 2026-10-08 22:20:27.085835
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "76d3c340ecde"
down_revision: str | None = "ebf02b9befa8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "decisions",
        "action",
        existing_type=sa.VARCHAR(length=12),
        type_=sa.String(length=16),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "decisions",
        "action",
        existing_type=sa.String(length=16),
        type_=sa.VARCHAR(length=12),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
