"""polymarket mapping

Revision ID: 7d74c9a09821
Revises: ab21c2196dc5
Create Date: 2026-10-08 21:18:52.564847
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "7d74c9a09821"
down_revision: str | None = "ab21c2196dc5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "polymarket_markets",
        sa.Column("mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "polymarket_markets", sa.Column("mapped_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("polymarket_markets", "mapped_at")
    op.drop_column("polymarket_markets", "mapping")
    # ### end Alembic commands ###
