"""decision layer

Revision ID: 901f9a92f5e0
Revises: 90a6d6f3ad18
Create Date: 2026-10-08 21:47:34.262409
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "901f9a92f5e0"
down_revision: str | None = "90a6d6f3ad18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cycles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("trigger", sa.String(length=80), nullable=True),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cycles_started_at"), "cycles", ["started_at"], unique=False)
    op.create_table(
        "agent_outputs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cycle_id", sa.BigInteger(), nullable=False),
        sa.Column("agent", sa.String(length=20), nullable=False),
        sa.Column("asset", sa.String(length=10), nullable=False),
        sa.Column("variant", sa.String(length=10), nullable=False),
        sa.Column("score", sa.Double(), nullable=False),
        sa.Column("confidence", sa.Double(), nullable=False),
        sa.Column("horizon", sa.String(length=6), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("risk_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_age_min", sa.Integer(), nullable=False),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["cycle_id"], ["cycles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_agent_outputs_cycle", "agent_outputs", ["cycle_id"], unique=False)
    op.create_table(
        "decisions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cycle_id", sa.BigInteger(), nullable=False),
        sa.Column("asset", sa.String(length=10), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("spot", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("valid_agents", sa.Integer(), nullable=False),
        sa.Column("formula_score", sa.Double(), nullable=True),
        sa.Column("pm1_direction", sa.String(length=6), nullable=True),
        sa.Column("pm2_direction", sa.String(length=6), nullable=True),
        sa.Column("agreement", sa.String(length=10), nullable=False),
        sa.Column("consensus_score", sa.Double(), nullable=True),
        sa.Column("direction", sa.String(length=6), nullable=False),
        sa.Column("conviction", sa.Double(), nullable=True),
        sa.Column("proposal", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.String(length=120), nullable=False),
        sa.Column("risk_rule_hits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("action", sa.String(length=12), nullable=False),
        sa.ForeignKeyConstraint(["cycle_id"], ["cycles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_decisions_asset_cycle", "decisions", ["asset", "cycle_id"], unique=False)
    op.create_table(
        "pm_proposals",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cycle_id", sa.BigInteger(), nullable=False),
        sa.Column("pm", sa.String(length=10), nullable=False),
        sa.Column("variant", sa.String(length=10), nullable=False),
        sa.Column("model", sa.String(length=60), nullable=False),
        sa.Column("asset", sa.String(length=10), nullable=False),
        sa.Column("direction", sa.String(length=6), nullable=False),
        sa.Column("entry_low", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("entry_high", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("stop", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("target", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("max_hold_hours", sa.Integer(), nullable=True),
        sa.Column("score", sa.Double(), nullable=False),
        sa.Column("conviction", sa.Double(), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("weighted_up", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("weighted_down", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["cycle_id"], ["cycles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_pm_proposals_cycle", "pm_proposals", ["cycle_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pm_proposals_cycle", table_name="pm_proposals")
    op.drop_table("pm_proposals")
    op.drop_index("ix_decisions_asset_cycle", table_name="decisions")
    op.drop_table("decisions")
    op.drop_index("ix_agent_outputs_cycle", table_name="agent_outputs")
    op.drop_table("agent_outputs")
    op.drop_index(op.f("ix_cycles_started_at"), table_name="cycles")
    op.drop_table("cycles")
    # ### end Alembic commands ###
