"""x posts

Revision ID: 90a6d6f3ad18
Revises: 7d74c9a09821
Create Date: 2026-10-08 21:37:13.417185
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "90a6d6f3ad18"
down_revision: str | None = "7d74c9a09821"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "x_posts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("author_id", sa.String(length=32), nullable=True),
        sa.Column("author", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("query_asset", sa.String(length=10), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("asset", sa.String(length=10), nullable=True),
        sa.Column("stance", sa.String(length=10), nullable=True),
        sa.Column("kind", sa.String(length=10), nullable=True),
        sa.Column("credibility", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("shock", sa.Boolean(), nullable=True),
        sa.Column("labeled_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_x_posts_asset_created", "x_posts", ["asset", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_x_posts_asset_created", table_name="x_posts")
    op.drop_table("x_posts")
    # ### end Alembic commands ###
