"""execution

Revision ID: cf62b3dcc4d9
Revises: 50fbca293312
Create Date: 2026-10-08 22:05:45.517417
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "cf62b3dcc4d9"
down_revision: str | None = "50fbca293312"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "control_requests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "equity_snapshots",
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("equity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("cash", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("open_positions", sa.Integer(), nullable=False),
        sa.Column("gross_exposure", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.PrimaryKeyConstraint("ts", "mode"),
    )
    op.create_table(
        "heartbeats",
        sa.Column("process", sa.String(length=20), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("detail", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("process"),
    )
    op.create_table(
        "paper_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("starting_capital", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("cash", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("equity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("fees_paid", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("interest_paid", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("liquidations", sa.Integer(), nullable=False),
        sa.Column("day_start_equity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("day_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("day_high_equity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("decision_id", sa.BigInteger(), nullable=True),
        sa.Column("cycle_id", sa.BigInteger(), nullable=True),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("asset", sa.String(length=10), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("direction", sa.String(length=6), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("qty", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("exit_price", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("leverage", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("margin", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("notional", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("borrowed", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("stop", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("target", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("trail_stop", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("max_hold_hours", sa.Integer(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_reason", sa.String(length=20), nullable=True),
        sa.Column("fees", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("interest", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("pnl", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("pnl_price_pct", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("pnl_margin_pct", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("liquidation_price", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("order_link_id", sa.String(length=36), nullable=True),
        sa.Column("x_post_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_link_id"),
    )
    op.create_index("ix_positions_status_asset", "positions", ["status", "asset"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("position_id", sa.BigInteger(), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("order_link_id", sa.String(length=36), nullable=False),
        sa.Column("exchange_order_id", sa.String(length=40), nullable=True),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("purpose", sa.String(length=10), nullable=False),
        sa.Column("qty", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("price", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("filled_qty", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("avg_price", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("fee", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["position_id"], ["positions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_link_id"),
    )
    op.create_index("ix_orders_position", "orders", ["position_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_orders_position", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_positions_status_asset", table_name="positions")
    op.drop_table("positions")
    op.drop_table("paper_account")
    op.drop_table("heartbeats")
    op.drop_table("equity_snapshots")
    op.drop_table("control_requests")
    # ### end Alembic commands ###
