"""perp metrics

Revision ID: ea0af7659176
Revises: 652b91d87761
Create Date: 2026-10-08 21:05:28.337692
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ea0af7659176"
down_revision: str | None = "652b91d87761"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "perp_metrics",
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("funding_rate", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("open_interest_value", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("mark_price", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.PrimaryKeyConstraint("symbol", "ts"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("perp_metrics")
    # ### end Alembic commands ###
