"""equity mode width

Revision ID: ebf02b9befa8
Revises: ffadfe44b719
Create Date: 2026-10-08 22:15:51.244440
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ebf02b9befa8"
down_revision: str | None = "ffadfe44b719"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "equity_snapshots",
        "mode",
        existing_type=sa.VARCHAR(length=8),
        type_=sa.String(length=16),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "equity_snapshots",
        "mode",
        existing_type=sa.String(length=16),
        type_=sa.VARCHAR(length=8),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
