"""x posts out

Revision ID: f345600719c0
Revises: 76d3c340ecde
Create Date: 2026-10-08 22:24:40.288582
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f345600719c0"
down_revision: str | None = "76d3c340ecde"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "x_posts_out",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("position_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("audit_ok", sa.Boolean(), nullable=False),
        sa.Column("audit_notes", sa.Text(), nullable=True),
        sa.Column("whitelist_ok", sa.Boolean(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("x_id", sa.String(length=32), nullable=True),
        sa.Column("reply_to_x_id", sa.String(length=32), nullable=True),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_x_posts_out_position", "x_posts_out", ["position_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_x_posts_out_position", table_name="x_posts_out")
    op.drop_table("x_posts_out")
    # ### end Alembic commands ###
