"""tracks and depth flag

Revision ID: ffadfe44b719
Revises: cf62b3dcc4d9
Create Date: 2026-10-08 22:14:11.786031
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ffadfe44b719"
down_revision: str | None = "cf62b3dcc4d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orderbook_snapshots",
        sa.Column("depth_truncated", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "paper_account",
        sa.Column("track", sa.String(length=8), nullable=False, server_default="primary"),
    )
    op.add_column(
        "positions",
        sa.Column("track", sa.String(length=8), nullable=False, server_default="primary"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("positions", "track")
    op.drop_column("paper_account", "track")
    op.drop_column("orderbook_snapshots", "depth_truncated")
    # ### end Alembic commands ###
