"""Style profile for the writer: built from the owner's own posts when available
(``app/social/style_profile.md``, generated by ``python -m app.social.style``), otherwise
the two example posts from the spec."""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

PROFILE = Path(__file__).with_name("style_profile.md")
FALLBACK = (
    "Examples of the voice: "
    "'Took a $SOL long at 74.10, 3x. The range finally broke and Polymarket odds on a green "
    "week went from 48 to 61%. Stop 72.30, target 78.' | "
    "'Closed $SOL at 77.60 after 9 hours. +4.7% on price, +13.6% on margin. Ran out of steam "
    "just before the target, I'll take it.'"
)


def load() -> str:
    if PROFILE.exists():
        return PROFILE.read_text().strip()[:3000]
    return FALLBACK


async def build(handle: str, count: int = 200) -> str:
    """Owned reads of the owner's recent posts, summarized into a style profile by the
    writer model. Costs about count × $0.005 in X reads; run once, re-run rarely."""
    from pydantic import BaseModel

    from app.config import get_secrets
    from app.data.x import XClient
    from app.llm import complete, load_prompt

    class Profile(BaseModel):
        profile: str

    async with XClient(get_secrets().x_bearer_token) as x:
        user = await x.user_by_username(handle)
        posts = await x.user_timeline(user.id, min(count, 100))
        if count > 100:
            posts += await x.user_timeline(user.id, count - 100)
    texts = [p.text for p in posts if p.text]
    archive_posts(handle, posts)
    result = await complete(
        "post_writer",
        Profile,
        prompt=load_prompt("style_profile"),
        user_text="\n---\n".join(texts[:count]),
    )
    PROFILE.write_text(result.parsed.profile.strip() + "\n")
    return result.parsed.profile


def archive_posts(handle: str, posts: list) -> int:  # type: ignore[type-arg]
    """Store the owner's own posts in x_posts (author = handle) for the no-repeat check."""
    from datetime import UTC, datetime

    from app.db.models import XPostRecord
    from app.db.session import new_session

    now = datetime.now(UTC)
    n = 0
    with new_session() as session:
        for p in posts:
            if session.get(XPostRecord, p.id) is None:
                session.add(
                    XPostRecord(
                        id=p.id,
                        author_id=p.author_id,
                        author=handle,
                        created_at=p.created_at,
                        fetched_at=now,
                        query_asset=None,
                        text=p.text,
                        labeled_at=now,
                        kind="other",
                    )
                )
                n += 1
        session.commit()
    return n


if __name__ == "__main__":
    from app.config import get_config

    print(asyncio.run(build(get_config().posting.handle)))
    sys.exit(0)
